services:
  nginx:
    image: nginx:stable
    ports:
      - "8090:80"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - back-end-laravel
  back-end-laravel:
    build:
      context: .
      dockerfile: /docker/laravel/Dockerfile
    restart: unless-stopped
    environment:
      - SESSION_DRIVER=redis
      - REDIS_HOST=cache
      - DB_CONNECTION=null
      - CACHE_STORE=redis
      - APP_URL=http://localhost:8090
    volumes:
      - ./app:/app/app
      - ./bootstrap:/app/bootstrap
      - ./config:/app/config
      - ./public:/app/public
      - ./resources:/app/resources
      - ./routes:/app/routes
      - ./storage:/app/storage
      - ./composer.json:/app/composer.json
      - ./.auth0.api.json:/app/.auth0.api.json
      - ./.auth0.app.json:/app/.auth0.app.json
    working_dir: /app
    depends_on:
      - front-end-vue
      - cache
  front-end-vue:
    build:
      context: .
      dockerfile: /docker/vue/Dockerfile
    restart: unless-stopped
    environment:
      - APP_URL=http://localhost:8090
    ports:
      - "5173:5173"
    volumes:
      - ./public:/app/public
      - ./resources:/app/resources
      - ./package.json:/app/package.json
      - ./vite.config.js:/app/vite.config.js
    working_dir: /app
  cache:
    image: redis:7.4.2
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local

